name: client_subscriber
description: "Client Subscriber"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.2.3
  pin_code_fields: ^8.0.1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  bloc: ^8.1.4
  dio: ^5.4.3+1
  animations: ^2.0.11
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
#  package_info_plus: ^8.0.0
  lottie: ^3.1.2
  simple_circular_progress_bar: ^1.0.2
  fluttertoast: ^8.2.5
  dotted_border: ^2.1.0
  adaptive_theme: ^3.6.0
  dotted_line: ^3.2.2
  flutter_timer_countdown: ^1.0.7
  weipl_checkout_flutter: ^1.0.7
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/

